version: '3'
services:
  db:
    image: postgres
  # webpacker:
  #   build: .
  #   command: bundle exec bin/webpack-dev-server
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8080:8080"
  web:
    build: .
    command: foreman start -f Procfile.dev 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      # - webpacker
